spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/instazoo
    username: root
    password: 587595
    driver-class-name: com.mysql.cj.jdbc.Driver
